### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by LackyPal** [Sparker-99/string-progressbar#1]
How can I set different line for current and total length. Something like the image below

![IMG_20201219_090736](https://user-images.githubusercontent.com/65214509/102679935-cee8bd00-41d9-11eb-8421-4aa373074d5a.jpg)

**Comment by Sparker-99** [comment]
The thing you are expecting is canvas package related not possible with strings. There might be a possibility of success try using custom emoji on `line` parameter.
